"use client";

import { motion } from "framer-motion";
import { Sparkles } from "lucide-react";

interface AIInsightCardProps {
  text: string;
}

export function AIInsightCard({ text }: AIInsightCardProps) {
  return (
    <motion.div
      className="relative overflow-hidden rounded-2xl border border-primary-muted bg-gradient-to-br from-primary-light via-surface to-accent-light p-5 shadow-sm"
      initial={{ opacity: 0, y: 12 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true }}
      transition={{ duration: 0.45, ease: "easeOut" }}
    >
      {/* Subtle glow */}
      <div
        aria-hidden="true"
        className="pointer-events-none absolute right-0 top-0 h-32 w-32 translate-x-8 -translate-y-8 rounded-full bg-primary/10 blur-2xl"
      />

      {/* Header */}
      <div className="mb-3 flex items-center gap-2.5">
        <div className="flex h-8 w-8 flex-shrink-0 items-center justify-center rounded-lg bg-primary/10 ring-1 ring-primary-muted">
          <Sparkles className="h-4 w-4 text-primary" aria-hidden="true" />
        </div>
        <div>
          <p className="text-xs font-bold text-primary">AI Analysis</p>
          <p className="text-[10px] text-foreground-subtle">Generated by ResuMind</p>
        </div>
      </div>

      {/* Content */}
      <p className="relative text-sm leading-relaxed text-foreground-muted">{text}</p>
    </motion.div>
  );
}
